ch99/blog/urls.py
from django.urls import path, re_path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.PostLV.as_view(), name='index'),
    path('post/', views.PostLV.as_view(), name='post_list'),
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),
    path('archive/', views.PostAV.as_view(), name='post_archive'),
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
    path('search/', views.SearchFormView.as_view(), name='search'),
    path('add/', views.PostCreateView.as_view(), name='add'),
    path('change/', views.PostChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
]

ch99/bookmark/urls.py
from django.urls import path
from . import views

app_name = 'bookmark'
urlpatterns = [
    path('', views.BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', views.BookmarkDV.as_view(), name='detail'),

    path('add/', views.BookmarkCreateView.as_view(), name='add'),
    path('change/', views.BookmarkChangeLV.as_view(), name="change"),
    path('<int:pk>/update/', views.BookmarkUpdateView.as_view(), name="update"),
    path('<int:pk>/delete/', views.BookmarkDeleteView.as_view(), name="delete"),
]

ch99/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static  # static()은 정적 파일을 처리하기 위해 그에맞는 URL패턴을 반환하는 함수
from django.conf import settings            # setting.py 에서 정의한 항목들을 담고 있는 객체를 가리킴
from .views import HomeView
from .views import UserCreateView, UserCreateDoneTV

# name인자는 템플릿에서 사용함
# path안에 url 넣어줄때 '/' 위치 잘넣자..안그럼 인식못함.
urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),

    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('photo/', include('photo.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #(prefix, view=, **kwargs)

ch99/photo/urls.py
from django.urls import path
from . import views

app_name = 'photo'
urlpatterns = [
    path('', views.AlbumLV.as_view(), name='index'),
    path('album', views.AlbumLV.as_view(), name='album_list'),
    path('album/<int:pk>/', views.AlbumDV.as_view(), name='album_detail'),
    path('photo/<int:pk>/', views.PhotoDV.as_view(), name='photo_detail'),

    path('album/add/', views.AlbumPhotoCV.as_view(), name='album_add'),
    path('album/change/', views.AlbumChangeLV.as_view(), name='album_change'),
    path('album/<int:pk>/update/', views.AlbumPhotoUV.as_view(), name='album_update'),
    path('album/<int:pk>/delete/', views.AlbumDelV.as_view(), name='album_delete'),
    path('photo/add/', views.PhotoCV.as_view(), name='photo_add'),
    path('photo/change/', views.photoChangeLV.as_view(), name='photo_change'),
    path('photo/<int:pk>/update/', views.PhotoUV.as_view(), name='photo_update'),
    path('photo/<int:pk>/delete/', views.PhotoDelV.as_view(), name='photo_delete'),
]

ch99/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">

    <title>{% block title %}Django Web Programming{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% block extra-style %}{% endblock %}

</head>

<body style="padding-top:90px;">

<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
  <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">Django - Python Web Programming</span>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item mx-1 btn btn-primary">
        <a  class="nav-link text-white" href="{% url 'home'%}">Home</a>
      </li>
       <li class="nav-item mx-1 btn btn-primary">
        <a  class="nav-link text-white" href="{% url 'bookmark:index'%}">Bookmark</a>
      </li>
      <li class="nav-item mx-1 btn btn-primary">
        <a  class="nav-link text-white" href="{% url 'blog:index' %}">Blog</a>
      </li>
      <li class="nav-item mx-1 btn btn-primary">
        <a  class="nav-link text-white" href="{% url 'photo:index' %}">Photo</a>
      </li>
      <li class="nav-item dropdown mx-1 btn btn-primary">
        <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown" >Util</a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'blog:post_archive' %}">Archive</a>
          <a class="dropdown-item" href="{% url 'blog:search' %}">Search</a>
        </div>
      </li>


      <li class="nav-item dropdown mx-1 btn btn-primary">
        <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Add</a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'bookmark:add' %}">Bookmark</a>
          <a class="dropdown-item" href="{% url 'blog:add' %}">Post</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="">Album</a>
          <a class="dropdown-item" href="">Photo</a>
        </div>
      </li>


      <li class="nav-item dropdown mx-1 btn btn-primary">
        <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Change</a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'bookmark:change' %}">Bookmark</a>
          <a class="dropdown-item" href="{% url 'blog:change' %}">Post</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="">Album</a>
          <a class="dropdown-item" href="">Photo</a>
        </div>
      </li>


    </ul>

    <form class="form-inline my-2" action="" method="post">{% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="global search" name="search_word">
    </form>

    <ul class="navbar-nav ml-5 mr-5">
      <li class="nav-item dropdown mx-1 btn btn-primary">
        {% if user.is_active %}
        <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
          <i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}&ensp;
        </a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
          <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
        </div>
        {% else %}
        <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
          <i class="fas fa-user"></i>&ensp;Anonymous&ensp;
        </a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'login' %}">Login</a>
          <a class="dropdown-item" href="{% url 'register' %}">Register</a>
        </div>
        {% endif %}
      </li>
    </ul>


  </div>
</nav>

<div class="container">
    {% block content%}{% endblock %}
</div>

{% block footer %}{% endblock %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/c082b0da57.js" crossorigin="anonymous"></script>
{% block extra-script%}{% endblock %}
</body>
</html>

ch99/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}home.html{% endblock %}

{% block extra-style %}
<style type="text/css">
.home-image{
  background-image:url("{% static 'img/lion.jpg' %}");
  background-repeat: no-repeat;
  background-position: center;
  background-size: 100%;
  height: 500px;
  border-top: 10px solid #ccc;
  border-bottom: 10px solid #ccc;
  padding: 20px 0 0 20px;
}
.title{
  color: #c80;
  font-weight: bold;
}
.powered {
  position: relative;
  top : 77%;
  color:#cc0;
  font-style: italic;
}
</style>
{% endblock %}

{% block content %}
  <div class="home-image">
    <h2 class="title">Django - Python Web Programming</h2>
    <h4 class="powered"><i class="fas fa-arrow-circle-right"></i> powered by django and bootstrap.</h4>
  </div>

  <hr style="margin: 10px 0;">

  <div class="row text-center">
    <div class="col-sm-6">
      <h3>Bookmark App</h3>
      <p>Bookmark is a Uniform Resource Identifier (URI)
        that is stored for later retrieval in any of various storage formats.
      You can store your own bookmarks by Bookmark application.
      It's also possible to update or delete your bookmarks.</p>
    </div>
    <div class="col-sm-6">
      <h3>Blog App</h3>
      <p>This application makes it possible to log daily events or write your own interests
      such as hobbies. techniques, etc.
      A typical blog conbines text, digital images, and links to other blogs, web pages, and other
      media related to its topic.</p>
    </div>
  </div>
{% endblock content %}


{% block footer %}
<footer class="fixed-bottom bg-info">
  <div class="text-while font-italic text-right mr-5">Copyright &copy; 2019 DjangoBook by shikim</div>
</footer>
{% endblock %}